
service: node-express-app

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  timeout: 10
  stage: production
  region: us-east-2

functions:
  api:
    handler: lambda.universal
    events:
      - http: ANY {proxy+}
      - http: ANY /